# Generated by Django 4.2 on 2023-05-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_newsitem_description_newsitem_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('code', models.CharField(max_length=64, verbose_name='код')),
            ],
            options={
                'verbose_name': 'тип помещения',
                'verbose_name_plural': 'типы помещения',
            },
        ),
        migrations.CreateModel(
            name='NumberOfRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HousingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание жилья')),
                ('published_at', models.DateTimeField(null=True, verbose_name='дата публикации')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='app_news.housingitem')),
            ],
        ),
    ]
