# Generated by Django 4.2 on 2023-05-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_housingtype_numberofrooms_housingitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingitem',
            options={'verbose_name': 'Жилье'},
        ),
    ]
