# Generated by Django 4.2 on 2023-05-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_alter_housingitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='app_news.housingtype'),
        ),
    ]
