# Generated by Django 4.2 on 2023-05-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_alter_housingitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberofrooms',
            name='housing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_news.housingitem'),
            preserve_default=False,
        ),
    ]
