# Generated by Django 4.1.7 on 2023-04-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.AddField(
            model_name='profile',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='profile_preview_directory_path'),
        ),
    ]
