# Generated by Django 4.1.7 on 2023-04-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_products_created_at_products_discount_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
