# Generated by Django 4.2 on 2023-05-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_remove_product_shops_shopstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='shopstock',
            options={'verbose_name': 'Остаток', 'verbose_name_plural': 'Остатки'},
        ),
    ]
