# Generated by Django 4.2 on 2023-05-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_remove_profile_agreement_accepted_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
