# Generated by Django 4.2 on 2023-05-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_shop_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
