# Generated by Django 4.2 on 2023-05-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_delete_product_delete_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
